// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieDB.Data;

#nullable disable

namespace MovieDB.Migrations
{
    [DbContext(typeof(MovieDataContext))]
    [Migration("20231114150918_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("MovieDB.Data.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("MovieGenre")
                        .HasColumnType("TEXT");

                    b.Property<string>("MovieName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Movie", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            MovieGenre = "Crime|Mystery|Thriller",
                            MovieName = "Sherlock Holmes and the Secret Weapon",
                            ReleaseDate = "09/29/2004"
                        },
                        new
                        {
                            Id = 2,
                            MovieGenre = "Animation|Children|Comedy|Romance",
                            MovieName = "Lady and the Tramp",
                            ReleaseDate = "09/05/1970"
                        },
                        new
                        {
                            Id = 3,
                            MovieGenre = "Documentary",
                            MovieName = "Collision: Christopher Hitchens vs. Douglas Wilson",
                            ReleaseDate = "12/04/1987"
                        },
                        new
                        {
                            Id = 4,
                            MovieGenre = "Documentary",
                            MovieName = "Cooking Up Dreams (De ollas y sueños)",
                            ReleaseDate = "12/14/2013"
                        },
                        new
                        {
                            Id = 5,
                            MovieGenre = "Animation",
                            MovieName = "Merry Madagascar",
                            ReleaseDate = "04/13/1953"
                        },
                        new
                        {
                            Id = 6,
                            MovieGenre = "Comedy|Sci-Fi",
                            MovieName = "Sleeper",
                            ReleaseDate = "07/02/2022"
                        },
                        new
                        {
                            Id = 7,
                            MovieGenre = "Comedy|Drama",
                            MovieName = "Article 99",
                            ReleaseDate = "05/21/1974"
                        },
                        new
                        {
                            Id = 8,
                            MovieGenre = "Adventure|Sci-Fi",
                            MovieName = "Battle in Outer Space",
                            ReleaseDate = "10/06/1990"
                        },
                        new
                        {
                            Id = 9,
                            MovieGenre = "Action|Adventure|Comedy",
                            MovieName = "The Pirates of Blood River",
                            ReleaseDate = "05/11/2009"
                        },
                        new
                        {
                            Id = 10,
                            MovieGenre = "Comedy",
                            MovieName = "Fun Size",
                            ReleaseDate = "06/30/1966"
                        },
                        new
                        {
                            Id = 11,
                            MovieGenre = "Drama",
                            MovieName = "Lenny",
                            ReleaseDate = "11/19/2011"
                        },
                        new
                        {
                            Id = 12,
                            MovieGenre = "Crime|Drama",
                            MovieName = "Sonny",
                            ReleaseDate = "06/12/1956"
                        },
                        new
                        {
                            Id = 13,
                            MovieGenre = "Thriller",
                            MovieName = "The Loft",
                            ReleaseDate = "06/11/2001"
                        },
                        new
                        {
                            Id = 14,
                            MovieGenre = "Adventure|Drama|Sci-Fi|Thriller",
                            MovieName = "Sunshine",
                            ReleaseDate = "11/16/1978"
                        },
                        new
                        {
                            Id = 15,
                            MovieGenre = "Comedy",
                            MovieName = "One Crazy Summer",
                            ReleaseDate = "07/15/2000"
                        },
                        new
                        {
                            Id = 16,
                            MovieGenre = "Crime|Documentary",
                            MovieName = "Prophet's Prey",
                            ReleaseDate = "11/05/1973"
                        },
                        new
                        {
                            Id = 17,
                            MovieGenre = "Comedy|Crime|Mystery|Thriller",
                            MovieName = "Confidentially Yours (Vivement dimanche!)",
                            ReleaseDate = "03/24/1958"
                        },
                        new
                        {
                            Id = 18,
                            MovieGenre = "Action|Adventure|Comedy|Fantasy|Romance",
                            MovieName = "Librarian: Quest for the Spear",
                            ReleaseDate = "12/05/2004"
                        },
                        new
                        {
                            Id = 19,
                            MovieGenre = "Drama",
                            MovieName = "The Power and the Glory",
                            ReleaseDate = "03/30/1950"
                        },
                        new
                        {
                            Id = 20,
                            MovieGenre = "Action|Adventure|Comedy",
                            MovieName = "Lupin the 3rd",
                            ReleaseDate = "10/08/1966"
                        },
                        new
                        {
                            Id = 21,
                            MovieGenre = "Drama|Fantasy|Mystery|Romance",
                            MovieName = "Dream (Bi-mong)",
                            ReleaseDate = "07/04/1986"
                        },
                        new
                        {
                            Id = 22,
                            MovieGenre = "Drama",
                            MovieName = "Neds",
                            ReleaseDate = "02/17/2020"
                        },
                        new
                        {
                            Id = 23,
                            MovieGenre = "Drama|Romance|Thriller",
                            MovieName = "Bodyguard",
                            ReleaseDate = "11/25/1992"
                        },
                        new
                        {
                            Id = 24,
                            MovieGenre = "Comedy",
                            MovieName = "Austin High",
                            ReleaseDate = "05/07/2010"
                        },
                        new
                        {
                            Id = 25,
                            MovieGenre = "Drama",
                            MovieName = "Vision (Vision - Aus dem Leben der Hildegard von Bingen)",
                            ReleaseDate = "10/12/2013"
                        },
                        new
                        {
                            Id = 26,
                            MovieGenre = "Crime|Drama",
                            MovieName = "Reconstruction (Anaparastasi)",
                            ReleaseDate = "03/19/2022"
                        },
                        new
                        {
                            Id = 27,
                            MovieGenre = "Comedy|Romance",
                            MovieName = "Fever Pitch",
                            ReleaseDate = "09/10/1973"
                        },
                        new
                        {
                            Id = 28,
                            MovieGenre = "Drama|Romance|War",
                            MovieName = "Holocaust",
                            ReleaseDate = "09/06/1958"
                        },
                        new
                        {
                            Id = 29,
                            MovieGenre = "Horror",
                            MovieName = "Black Moon",
                            ReleaseDate = "05/14/1964"
                        },
                        new
                        {
                            Id = 30,
                            MovieGenre = "Comedy|Fantasy|Horror|Thriller",
                            MovieName = "Witches of Eastwick",
                            ReleaseDate = "06/12/1987"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
